import { Bookmark, Share2, Zap } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

interface Creator {
  name: string
  npub: string
}

interface NewsletterPreviewProps {
  title: string
  date: string
  content: string
  topics: string[]
  creators: Creator[]
}

export default function NewsletterPreview({ title, date, content, topics, creators }: NewsletterPreviewProps) {
  return (
    <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden">
      <div className="p-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-xl font-bold">{title}</h2>
            <p className="text-sm text-gray-400">{date}</p>
          </div>
          <div className="flex gap-2">
            <Button variant="ghost" size="icon" className="text-gray-400 hover:text-purple-400">
              <Bookmark className="h-5 w-5" />
            </Button>
            <Button variant="ghost" size="icon" className="text-gray-400 hover:text-purple-400">
              <Share2 className="h-5 w-5" />
            </Button>
          </div>
        </div>

        <div
          className="prose prose-invert max-w-none mb-4 text-gray-300"
          dangerouslySetInnerHTML={{ __html: content }}
        />

        <div className="flex flex-wrap gap-2 mb-4">
          {topics.map((topic) => (
            <Badge key={topic} variant="outline" className="bg-gray-800 text-gray-300 border-gray-700">
              {topic}
            </Badge>
          ))}
        </div>

        <div className="bg-gray-800/50 p-3 rounded-lg">
          <div className="flex items-center justify-between mb-2">
            <h4 className="text-sm font-medium">Content Creators</h4>
            <Button variant="ghost" size="sm" className="h-7 px-2 text-amber-400">
              <Zap className="h-3.5 w-3.5 mr-1" />
              Zap All
            </Button>
          </div>
          <div className="space-y-2">
            {creators.map((creator) => (
              <div key={creator.npub} className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-6 h-6 rounded-full bg-gray-700 flex items-center justify-center text-xs">
                    {creator.name.charAt(0)}
                  </div>
                  <span className="text-sm">{creator.name}</span>
                  <span className="text-xs text-gray-500">{creator.npub}</span>
                </div>
                <Button variant="ghost" size="sm" className="h-6 px-2 text-amber-400">
                  <Zap className="h-3 w-3 mr-1" />
                  Zap
                </Button>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="bg-gray-800/50 px-6 py-3 flex items-center justify-between">
        <p className="text-sm text-gray-400">Generated by AI from Nostr content</p>
        <Button variant="link" className="text-purple-400 p-0 h-auto">
          View sources
        </Button>
      </div>
    </div>
  )
}
